#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys

/bin/mknod -m 0666 /dev/null c 1 3
/bin/mknod -m 0666 /dev/random c 1 8
/bin/mknod -m 0666 /dev/urandom c 1 9

/bin/mknod /dev/ttyS0 c 4 64

/bin/rm -f /dev/console
/bin/ln -s /dev/ttyS0 /dev/console

/bin/mkdir -p /var/log
/sbin/syslogd -b 5
klogd

exec /sbin/init
