#!/bin/busybox sh
mkdir -pv /sbin
/bin/busybox --install -s

MAC=`od -An -N4 -t xC /dev/urandom | xargs | awk '{ gsub(" ",":",$0); print $0 }'`

ip link set up dev eth0
ip link set up dev wl1

ip link set dev eth0 address 00:${MAC}:01
ip link set dev wl1 address 00:${MAC}:02

echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"

insmod /lib/modules/"$(uname -r)"/extra/mesh.ko
ip link add name mesh type meshif

ip link set dev mesh up

ip link set eth0 master mesh

ip link set eth1 down
ip link set eth1 name tap0
ip link set tap0 up
ip addr flush tap0
ip addr add 192.168.90.1/24 dev tap0

ip link

